# Generated by Django 5.2.11 on 2026-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_attending',
            field=models.CharField(choices=[('2026-01-23', '2026-01-23'), ('2026-01-24', '2026-01-24'), ('2026-01-25', '2026-01-25')], default='2026-03-21', max_length=20, verbose_name='Date of Attending'),
        ),
    ]
