# Generated by Django 5.2.11 on 2026-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_date_of_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_attending',
            field=models.CharField(choices=[('2026-03-21', '2026-03-21'), ('2026-03-22', '2026-03-22')], default='2026-03-21', max_length=20, verbose_name='Date of Attending'),
        ),
    ]
